<?php
$ejercicios = [
    'tipografia' => [
        1 => "Trazar en renglón doble línea las letras semejantes en trazado como <i>c–a-b-d-g-q-o</i>. Luego escribir palabras con dichas letras, por copiado, finalmente por dictado.",
        2 => "Trazar en renglón doble línea las letras semejantes en trazado como <i>c–a-b-d-g-q-o</i>. Luego escribir palabras con dichas letras, por copiado, finalmente por dictado.",
        3 => "Copiar el alfabeto completo; escribir el alfabeto completo en 1 minuto o chequear cuántas letras se logran en dicho tiempo. Luego monitorear que el trazado sea el adecuado.",
        4 => "Monitorear el uso continuo de una tipografía mediante lista de cotejo o revisar escritos de otros para corroborar precisión y continuidad en la tipografía"
    ],
    'claridad' => [
        1 => "Hacer hojas de trabajo de trazos y caligrafía en renglón pautado o doble línea y con un modelo de trazo de referencia. <u>Ejemplo</u>: trazar letras como 'g', 'l', 'b' repetidamente en una hoja de caligrafía.",
        2 => "Hacer hojas de trabajo de trazos y caligrafía en renglón pautado o doble línea y con un modelo de trazo de referencia. <u>Ejemplo</u>: trazar letras como 'f', 'e', 'h' repetidamente en una hoja de caligrafía.",
        3 => "Escribir palabras difíciles y revisarlas. Ejemplo: escribir palabras como 'paralelogramo', 'cincuenta', 'extraterrestre' y asegurarse de que cada letra sea clara y completa.",
        4 => "Copiar fragmentos de textos con énfasis en la precisión del trazado. Ejemplo: copiar un párrafo de un libro favorito, asegurándose de que cada letra y trazo sea preciso y claro."
    ],
    'tamaño' => [
        1 => "Realizar ejercicios de caligrafía en hojas con letras de diferentes tamaños. <u>Ejemplo</u>: escribir la letra 'a' pequeña y grande chata utilizando renglón pautado o doble línea.",
        2 => "Realizar ejercicios de caligrafía en hojas con palabras de diferentes tamaños. <u>Ejemplo</u>: escribir la palabra 'casa' en dos tamaños, 'había' en dos tamaños y 'vacaciones' en dos tamaños utilizando renglón pautado o doble línea.",
        3 => "Escribir párrafos cortos en renglón pautado o doble línea y revisarlos. <u>Ejemplo</u>: escribir un párrafo sobre el fin de semana usando renglón pautado o doble línea para mantener el tamaño de las letras consistente.",
        4 => "Redactar una breve historia o un diario manteniendo el tamaño uniforme de las letras ahora sin renglón pautado. <u>Ejemplo</u>: escribir una historia de una página sobre una aventura imaginaria, asegurándose de que todas las letras mantengan un tamaño coherente."
    ],
    'presion' => [
        1 => "Escribir una oración utilizando una presión ligera, media y fuerte, y luego comparar la claridad y legibilidad. <u>Ejemplo</u>: escribir una frase como 'El sol brilla' con diferentes niveles de presión y analizar cuál es más legible. Actividad: Usar lápices de diferente dureza (HB, 2B, 4B) para ver cómo cambia la presión. Juego: Hacer ejercicios de caligrafía en arena o con pintura de dedos para sentir la presión.",
        2 => "Escribir varias líneas de texto utilizando una presión ligera, media y fuerte, y luego comparar la claridad y legibilidad. <u>Ejemplo</u>: escribir una frase como 'El sol brilla' con diferentes niveles de presión y analizar cuál es más legible. Actividad: Usar lápices de diferente dureza (HB, 2B, 4B) para ver cómo cambia la presión. Juego: Hacer ejercicios de caligrafía en arena o con pintura de dedos para sentir la presión.",
        3 => "Escribir un párrafo asegurándose de mantener una presión constante. <u>Ejemplo</u>: escribir un párrafo sobre una actividad diaria, manteniendo la misma presión en todas las letras. Actividad: escribir en papel cuadriculado para observar y mantener la presión uniforme. Juego: Realizar ejercicios de caligrafía con plumas estilográficas para controlar mejor la presión",
        4 => "Escribir un texto expositivo, enfocándose en mantener una presión constante. <u>Ejemplo</u>: escribir un texto de una página sobre un tema de interés, revisando que la presión sea uniforme. Actividad: revisar y corregir textos anteriores para identificar variaciones en la presión y mejorar. Juego: Participar en concursos de escritura donde la presión y legibilidad sean evaluadas."
    ],
    'emplazamiento_renglon' => [
        1 => "Escribir oraciones asegurándose de que todas las letras se mantengan dentro del renglón. <u>Ejemplo</u>: escribir la frase 'El perro juega en el parque' y revisar que todas las letras estén alineadas con el renglón. Actividad: usar papel con líneas guía adicionales para ayudar a mantener el emplazamiento. Juego: jugar a escribir en renglones de colores diferentes para hacer la actividad más divertida.",
        2 => "Escribir oraciones asegurándose de que todas las letras se mantengan dentro del renglón. <u>Ejemplo</u>: escribir la frase 'El perro juega en el parque' y revisar que todas las letras estén alineadas con el renglón. Actividad: usar papel con líneas guía adicionales para ayudar a mantener el emplazamiento. Juego: jugar a escribir en renglones de colores diferentes para hacer la actividad más divertida.",
        3 => "Escribir un párrafo asegurándose de que todas las letras se mantengan alineadas con el renglón. <u>Ejemplo</u>: escribir un párrafo describiendo una imagen, manteniendo todas las letras alineadas con el renglón. Actividad: escribir en papel rayado y luego en papel blanco para observar la diferencia en el emplazamiento. Juego: hacer ejercicios de caligrafía con letras mayúsculas y minúsculas para mantener el emplazamiento correcto.",
        4 => "Escribir una historia breve, asegurándose de mantener todas las letras alineadas con el renglón. <u>Ejemplo</u>: escribir sobre algo que me pasó muy gracioso o que me sorprendió y revisar que todas las letras estén bien emplazadas en el renglón. Actividad: revisar y corregir escritos anteriores para identificar problemas de emplazamiento y mejorar."
    ],
    'repeticiones' => [
        1 => "Escribir oraciones usando sinónimos en lugar de repetir palabras. <u>Ejemplo</u>: escribir la frase 'El gato es bonito. El felino tiene ojos verdes'. <u>Actividad</u>: Hacer una lista de palabras comunes y encontrar sinónimos para cada una. Ejercicio de sinónimos: Instrucción: Escribe una lista de 10 palabras comunes y encuentra al menos dos sinónimos para cada una. Ejemplo: Grande: enorme, gigante. Bonito: hermoso, lindo. Ejemplo: Escribir un párrafo sobre una persona sin repetir su nombre, usando pronombres como 'él' o 'ella'.",
        1 => "Escribir oraciones usando sinónimos en lugar de repetir palabras. <u>Ejemplo</u>: escribir la frase 'El gato es bonito. El felino tiene ojos verdes'. <u>Actividad</u>: Hacer una lista de palabras comunes y encontrar sinónimos para cada una. Ejercicio de sinónimos: Instrucción: Escribe una lista de 10 palabras comunes y encuentra al menos dos sinónimos para cada una. Ejemplo: Grande: enorme, gigante. Bonito: hermoso, lindo. Ejemplo: Escribir un párrafo sobre una persona sin repetir su nombre, usando pronombres como 'él' o 'ella'.",
        3 => "Ejercicio: Escribir un párrafo utilizando diferentes estructuras de oraciones y pronombres. <u>Ejemplo</u>: 'Juan fue al parque. Allí, él jugó con sus amigos. Luego, todos fueron a casa de Juan'. Actividad: Reescribir un texto reemplazando las palabras repetidas con sinónimos o pronombres. Juego: Crear tarjetas con palabras y sus sinónimos y practicar reemplazándolos en oraciones. Ejercicio de variación de oraciones: Instrucción: Escribe un párrafo sobre tu día utilizando diferentes estructuras de oraciones y pronombres para evitar repeticiones. Ejemplo: 'Esta mañana, Marta se levantó temprano. Ella preparó el desayuno y luego salió a correr. Más tarde, fue a trabajar'. Actividad de reescritura: Instrucción: Reescribe un párrafo de un libro reemplazando palabras repetidas con sinónimos y pronombres. Texto original:'El coche era rápido. El coche también era rojo'. Reescrito: 'El coche era rápido. Además, era de color rojo'.",
        4 => "Ejercicio: Escribir un texto breve, revisarlo y reemplazar palabras repetidas con sinónimos o reformular las oraciones. <u>Ejemplo</u>: 'El alumno presentó su informe. El informe contenía datos importantes. El informe fue bien recibido por la maestra'. Actividad: Revisar un texto y asegurarse de que no haya repeticiones innecesarias. Juego: Jugar a un juego de edición en el que se debe eliminar repeticiones de un texto dado y reformular oraciones."
    ],
    'vocabulario' => [
        1 => "Leer y hacer listas de nuevas palabras. <u>Ejemplo</u>: Leer un cuento y listar nuevas palabras como 'valiente', 'explorar', 'aventura' o brindar una imagen y pensar palabras que califican; ampliar oraciones agregando adjetivos.",
        2 => "Leer y hacer listas de nuevas palabras. <u>Ejemplo</u>: Leer un cuento y listar nuevas palabras como 'valiente', 'explorar', 'aventura' o brindar una imagen y pensar oraciones agregando un complemento de modo, lugar o tiempo .",
        3 => "Escribir descripciones de objetos o lugares. <u>Ejemplo</u>: Describir una habitación favorita, incluyendo detalles sobre colores, formas y objetos.",
        4 => "Describir lugares, personas, sentimientos o comparar personajes utilizando sinónimos y antónimos. <u>Ejemplo</u>: Escribir una reflexión sobre personajes antagónicos de una historia o describir detalladamente un suceso o lugar, asegurándose de usar sinónimos para evitar repeticiones y antónimos para mostrar contrastes."
    ],
    'conectores' => [
        1 => "Hacer esquemas o mapas mentales antes de redactar. <u>Ejemplo</u>: Crear un esquema para un cuento con los siguientes puntos: inicio (presentación de personajes), desarrollo (problema), y desenlace (solución) y brindarles ideas de conectores para cada sección.",
        2 => "Hacer esquemas o mapas mentales antes de redactar. <u>Ejemplo</u>: Crear un esquema para un cuento con los siguientes puntos: inicio (presentación de personajes), desarrollo (problema), y desenlace (solución) y elegir el conector entre dos o tres dados.",
        3 => "Escribir párrafos con conectores lógicos. <u>Ejemplo</u>: Escribir un párrafo sobre un evento en orden cronológico usando conectores como 'primero', 'después', 'finalmente'.",
        4 => "Escribir historias con revisiones de coherencia. <u>Ejemplo</u>: Escribir una historia y revisar que cada evento tenga una conexión lógica con el siguiente y que se adecúe a la estructura textual."
    ],
    'longitud' => [
        1 => "Escribir oraciones sobre imágenes. <u>Ejemplo</u>: Ver una imagen de un perro y escribir 'El perro juega en el parque'.",
        2 => "Escribir oraciones sobre imágenes. <u>Ejemplo</u>: Ver una imagen de un perro y escribir 'El perro juega en el parque'pero agregarle alguna descripción.",
        3 => "Escribir un párrafo sobre un tema conocido o apoyándose en viñetas. <u>Ejemplo</u>: Escribir un párrafo sobre el último viaje realizado, incluyendo detalles y emociones; luego contabilizar oraciones o cantidad de palabras.",
        4 => "Escribir historias o informes sobre temas de interés o sobre un animal que previamente se investigue o reformular una historia leída o escuchada agregándole algún elemento novedoso que la personalice. Ejemplo: Escribir una historia de tres páginas sobre una aventura imaginaria o una versión personal sobre un cuento clásico; luego contabilizar oraciones o palabras."
    ],
    'puntuacion' => [
        1 => "Escribir oraciones cortas y añadir puntuación correcta. <u>Ejemplo</u>: Pedirle que revise si aparece la conjunción “y” y reemplazarla por un punto o si quiere contar varias cosas usar la coma para enumerar.",
        2 => "Escribir oraciones cortas y añadir puntuación correcta. <u>Ejemplo</u>: Pedirle que revise si aparece la conjunción “y” y reemplazarla por un punto; explicitar que cada oración es una idea y que relea para contar cuántas ideas tiene.",
        3 => "Revisar y corregir la puntuación en textos dados. <u>Ejemplo</u>: Corregir un texto dado, añadiendo comas, puntos y otros signos de puntuación donde sea necesario; practicar escribir un diálogo entre dos personajes de un cuento insertándole algún condimento gracioso o una conversación sobre un tema que al niño le interese.",
        4 => "Escribir y revisar historias con atención a la puntuación. <u>Ejemplo</u>: Escribir una historia de varias páginas y con diálogo; luego revisar el uso correcto de comas, puntos y otros signos de puntuación."
    ],
    'uso_mayuscula' => [
        1 => "Escribir oraciones sencillas asegurándose de usar mayúsculas al inicio y en nombres. <u>Ejemplo</u>: 'El gato corre.' 'María juega en el parque.' 'Buenos Aires es la capital de Argentina'. Revisar el propio escrito y sustituir la conjunción “y” por punto y luego poner mayúscula la siguiente palabra. Ejemplo: El ratón se comió un queso y se metió nuevamente en su casa y lo hizo rápido porque tenía miedo del gato. Versión corregida: El ratón se comió un queso. Se metió nuevamente en su casa. Lo hizo rápido porque tenía miedo del gato. Actividad: Leer un texto corto y subrayar las letras mayúsculas. Juego: Jugar a identificar errores de mayúsculas en oraciones mezcladas.",
        2 => "Escribir oraciones sencillas asegurándose de usar mayúsculas al inicio y en nombres. <u>Ejemplo</u>: 'El gato corre.' 'María juega en el parque.' 'Buenos Aires es la capital de Argentina'. Revisar el propio escrito y sustituir la conjunción “y” por punto y luego poner mayúscula la siguiente palabra. Ejemplo: El ratón se comió un queso y se metió nuevamente en su casa y lo hizo rápido porque tenía miedo del gato. Versión corregida: El ratón se comió un queso. Se metió nuevamente en su casa. Lo hizo rápido porque tenía miedo del gato. Actividad: Leer un texto corto y subrayar las letras mayúsculas. Juego: Jugar a identificar errores de mayúsculas en oraciones mezcladas.",
        3 => "Escribir un párrafo sobre un día típico utilizando mayúsculas correctamente. <u>Ejemplo</u>: 'El lunes, Juan fue a la escuela. En diciembre, celebramos la Navidad'. Actividad: Corregir un texto donde se hayan omitido mayúsculas. Juego: Hacer tarjetas con palabras que deben llevar mayúsculas y clasificarlas.",
        4 => "Escribir un texto breve utilizando correctamente mayúsculas en siglas y títulos de obras. <u>Ejemplo</u>: 'La OMS (Organización Mundial de la Salud) ha emitido nuevas directrices'. Leí 'Cien años de soledad' de Gabriel García Márquez'. Actividad: Revisar un texto académico y asegurarse de que todas las mayúsculas estén correctamente usadas. Juego: Crear oraciones complejas con varias palabras que requieran mayúsculas y pedir a los estudiantes que las corrijan."
    ],
    'correspondencia_fonologica' => [
        1 => "Jugar a juegos de fonética y segmentación. <u>Ejemplo</u>: Segmentar la palabra 'elefante' en sílabas: e-le-fan-te; luego pedir que deletree por el nombre de la letra, sin mirar la palabra escrita.",
        2 => "Jugar a juegos de fonética y segmentación. <u>Ejemplo</u>: Segmentar la palabra 'elefante' por sus letras; jugar a cambiar un sonido para ver qué palabra queda. Ejemplo: cama si cambio la m por la s queda casa.",
        3 => "Leer y escribir palabras con sonidos similares. <u>Ejemplo</u>: Practicar palabras con sílabas complejas de estructura ccv o ccvc u otras como: principio, tranquera, ambiente; cien vs quien; queso vs ceso; genio, gente vs jengibre.",
        4 => "Realizar dictados y revisar errores fonológicos. <u>Ejemplo</u>: Dictar palabras complejas y revisar juntos los errores, como 'extravagante', 'fotografía'."
    ],
    'correspondencia_ortografica' => [
        1 => "Hacer ejercicios de ortografía de palabras comunes. <u>Ejemplo</u>: Practicar la diferencia entre 'b' y 'v' con palabras como 'burro' y 'vaca'; modelar y explicar reglas simples y luego dictar o bien que escriban un renglón entero con dicha palabra.",
        2 => "Hacer ejercicios de ortografía de palabras comunes. <u>Ejemplo</u>: Practicar la diferencia entre 'c' y 's' o el uso de la h en palabras frecuentes. Pedirles que escriban un renglón entero de cada palabra y luego tomar dictado.",
        3 => "Escribir y revisar textos por errores ortográficos. <u>Ejemplo</u>: Escribir un párrafo sobre un tema de interés y revisar los errores ortográficos, como el uso de 'c' y 'z', 'g' y 'j'. Practicar el uso de 's' y 'c' con palabras como 'casa' y 'cena' o 'ha'y y 'ay', o 'ves' y 'vez' .",
        4 => "Redactar historias y revisar la ortografía. <u>Ejemplo</u>: Escribir un textos sobre un tema investigado, revisando detalladamente la ortografía con una lista de cotejo que contenga reglas ortográficas."
    ]
];
?>